- name: Simple Slack Notify

  # You may pin to the exact commit or the version.
  # uses: edge/simple-slack-notify@3438f95ccd2328cf20e8fa676fcf2dcf36b2b51e
  
  uses: edge/simple-slack-notify@1.0.4
  
  with:
    # The channel you want to send to, such as '#general'
    channel: '#scooter-ms'
    # Used to override the default username
    username: 'GH-Bot'
    # The color you want to use, can be good, danger, warning or a hex code
